### PR TITLE
chore: gitignore improvement 

### PR DESCRIPTION
**Pull request by 0xf333**
Hi guys,
I've updated the `.gitignore` to include a more comprehensive set of patterns to match files and directories at any level in this repo. This will help prevent unwanted files from sneaking into commits and ensure that the repo stays clean and organized.

# Summary of change

**Here's a quick summary of the changes:**
- Added patterns for commonly ignored Rust files and directories
- Included IDE/editor specific patterns for better compatibility
- Made sure the patterns work for complex project structures with multiple subdirectories

# Acceptance Checklist

## Feature (non-breaking change which adds functionality)

- [x] Have you **_seen it working_** in a development environment?

### CODE REVIEW

**Comment by 0xf333** [comment]
Hi @AwesomeIbex,
Feel free to let me know if you have any questions .

**Comment by AwesomeIbex** [comment]
Awesome sir!

Please can you update your commit message to follow https://www.conventionalcommits.org/en/v1.0.0/ - I'll be happy to merge then.

**Comment by 0xf333** [comment]
> Awesome sir!
> 
> Please can you update your commit message to follow https://www.conventionalcommits.org/en/v1.0.0/ - I'll be happy to merge then.

Hi @AwesomeIbex,
Thanks for the feedback, I appreciate it.
The commit message has now been updated as per your request.

**Comment by AwesomeIbex** [comment]
> @AwesomeIbex,
> 
> Further edit made to the commit message to pass the automated checks.
> 
> 1. The header is now within the 100-character limit.
> 2. The body's lines are not longer than 100 characters.
> 3. The footer has a leading blank line.

@0xf333  haha! You're almost there, there is one line that is 132 chars, this normally gets people with commitlint. I'd edit them myself but I don't wanna steal your commit.

**Comment by palozano** [comment]
Hi @0xf333! 

If you see the checks, there's one saying `"Lint Commit Messages / commitlint (pull_request) Failing after 11s"`.

If you click on Details, it takes you to the [output](https://github.com/t3rn/xbi/actions/runs/4744227824/jobs/8445457337?pr=48) of the tool, where you can see this:
Captura de pantalla 2023-05-01 a las 14 57 02

I've highlighted the line where it tells you what's failing. The header of the commit is 132 chars long.

You have correctly updated the commit message and it's much better now, however, the previous commit with the wrongly formated message is still in the PR (see [here](https://github.com/t3rn/xbi/pull/48/commits), there are two commits).

You can either **squash** them and keep the good message (since both are basically the same feature), or interactively rebase the commits so you are able to **reword** the message. Check this [page](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to learn how to do it.

**Comment by palozano** [comment]
@0xf333, looks good to me! Good job!

**Comment by 0xf333** [comment]
> @0xf333, looks good to me! Good job!

Thanks

**Pull request merged**
